/**
 * Reconstruct readable `CREATE` DDL from a {@link SchemaSnapshot}.
 *
 * This is a best-effort, dependency-free rendering for the Schema → SQL view and the "copy schema as
 * SQL" action — not a migration tool. It emits `CREATE TABLE` statements (columns, defaults,
 * nullability, primary keys, and inline foreign-key references), followed by any extensions. It is
 * intentionally conservative: it never invents constraints it cannot see in the snapshot.
 */
import type { SchemaSnapshot, TableInfo } from '../types/schema.js';
import { quoteIdent } from './statements.js';

function columnLine(col: TableInfo['columns'][number]): string {
  const parts = [`  ${quoteIdent(col.name)} ${col.dataType}`];
  if (!col.nullable) parts.push('NOT NULL');
  if (col.defaultValue) parts.push(`DEFAULT ${col.defaultValue}`);
  return parts.join(' ');
}

/** Render a single table's `CREATE TABLE` statement. */
export function tableToSql(table: TableInfo): string {
  const lines = table.columns.map(columnLine);

  const pk = table.columns.filter((c) => c.isPrimaryKey).map((c) => quoteIdent(c.name));
  if (pk.length > 0) {
    lines.push(`  PRIMARY KEY (${pk.join(', ')})`);
  }

  for (const col of table.columns) {
    if (col.references) {
      const target = `${quoteIdent(col.references.schema)}.${quoteIdent(col.references.table)}`;
      lines.push(
        `  FOREIGN KEY (${quoteIdent(col.name)}) REFERENCES ${target} (${quoteIdent(
          col.references.column,
        )})`,
      );
    }
  }

  const qualified = `${quoteIdent(table.schema)}.${quoteIdent(table.name)}`;
  const header = table.kind === 'view' ? `-- view ${qualified}` : '';
  const body = `CREATE TABLE ${qualified} (\n${lines.join(',\n')}\n);`;
  return header ? `${header}\n${body}` : body;
}

/** Render the whole snapshot as a single SQL document. */
export function schemaToSql(snapshot: SchemaSnapshot): string {
  const sections: string[] = [
    `-- Schema dump generated by Swyftgrids on ${new Date(snapshot.capturedAt).toLocaleString()}`,
    `-- ${snapshot.schemas.length} schema(s), ${snapshot.tables.length} table(s)`,
  ];

  if (snapshot.extensions.length > 0) {
    sections.push(
      '\n-- Extensions',
      snapshot.extensions
        .map((e) => `CREATE EXTENSION IF NOT EXISTS ${quoteIdent(e.name)};`)
        .join('\n'),
    );
  }

  const schemasToCreate = snapshot.schemas.map((s) => s.name).filter((name) => name !== 'public');
  if (schemasToCreate.length > 0) {
    sections.push(
      '\n-- Schemas',
      schemasToCreate.map((name) => `CREATE SCHEMA IF NOT EXISTS ${quoteIdent(name)};`).join('\n'),
    );
  }

  if (snapshot.tables.length > 0) {
    sections.push('\n-- Tables', snapshot.tables.map(tableToSql).join('\n\n'));
  }

  return sections.join('\n') + '\n';
}
